# Pin spectific verison
FROM node:18.19-bullseye AS build

# Spectify working driectory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]