# Pin specific version
# Use slim for reduced image size
FROM node:18.19.0-bullseye-slim

# Specific working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

RUN npm install

# Copy remaining source code AFTER installing dependencies.
# Again, copy only the necessary files
COPY ./src .

CMD [ "node", "index.js" ]