# Pin specific version
# Use slim for reduced image size
FROM node:18.9.0-bullseye-slim

# Specific working directory other than /
WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD [ "node", "index.js" ]