# Pin specific version for stability
# Use debain fro easier build utilities
FROM golang:1.21-bullseye AS build

# cn timeout problem
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

WORKDIR /app

# Copy only files required to install dependencies (better layer caching)
COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Compile application during build rather that at runtime
RUN go build -o api-golang

CMD [ "go", "run", "./main.go" ]